const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
function store(){ const data=new Map();const c=vm.createContext({localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../tests-store.js'),'utf8'),c);return code=>vm.runInContext(code,c); }
test('resultados limitados à etapa alvo e preservados após edição das etapas globais',()=>{const run=store();run("var sc=newTestExecution({id:'one',nome:'Teste',tipo:'Manual',etapaAlvo:'Criação de Pedido'});sc.etapas={'Simulação':'OK','Criação de Pedido':'OK'}");assert.equal(run('execStatus(sc)'),'OK');run("testStages.unshift('Nova etapa');testStages.splice(testStages.indexOf('Simulação'),1)");assert.equal(run('execStatus(sc)'),'OK');assert.equal(run('executionStages(sc).length'),2);});
test('plano vazio, pendente ou falhando não pode receber aceite',()=>{const run=store();assert.equal(run('hoComplete({cenarios:[]})'),false);run("var sc=newTestExecution({id:'one',nome:'Teste',tipo:'Automática',etapaAlvo:'Simulação'});var plan={cenarios:[sc]}");assert.equal(run('hoComplete(plan)'),false);run("sc.etapas['Simulação']='Falhou'");assert.equal(run('hoComplete(plan)'),false);run("sc.etapas['Simulação']='OK'");assert.equal(run('hoComplete(plan)'),true);});
test('produção começa pendente, sem pedido e evidências de HO, preservando a origem',()=>{const run=store();run("var sc=newTestExecution({id:'one',nome:'Teste',tipo:'Manual',etapaAlvo:'Simulação'});sc.etapas['Simulação']='OK';sc.pedido='123';sc.jira='HO-123';var prod=productionFromHO('ISS-1',sc)");assert.equal(run('execStatus(prod)'),'Pendente');assert.equal(run('prod.pedido'),'');assert.equal(run('prod.jira'),'');assert.equal(run('prod.sourceIssueId'),'ISS-1');assert.equal(run('prod.sourceExecutionId===sc.id'),true);run("prod.etapas['Simulação']='Falhou'");assert.equal(run('execStatus(sc)'),'OK');});
test('planos e trilhas persistem em stores separados',()=>{const run=store();run("saveTestData(hoPlansKey,{'ISS-1':{cenarios:[]}});saveTestData(testTrailsKey,[{id:'t1',nome:'Smoke',casoIds:['cat-001']}])");assert.equal(run("hoPlans()['ISS-1'].cenarios.length"),0);assert.equal(run('testTrails()[0].nome'),'Smoke');});
test('sugestões usam vínculos explícitos, qualquer componente, sem duplicar e ignoram inativos',()=>{const run=store();run("var catalog=[{id:'a',nome:'A',ativo:true,componentes:[' API-CREDITO ','web-credito','api-credito']},{id:'b',nome:'B',ativo:true,componentes:['web-credito']},{id:'c',nome:'C',ativo:false,componentes:['api-credito']},{id:'d',nome:'Sem vínculo',ativo:true},{id:'e',nome:'Prefixo',ativo:true,componentes:['api']}];var suggestions=suggestedTests({servicos:['api-credito','WEB-CREDITO','api-outro']},catalog)");assert.equal(run('suggestions.length'),2);assert.equal(run('suggestions[0].caso.id'),'a');assert.equal(run('suggestions[0].componentes.length'),2);assert.equal(run("suggestedTests({servicos:['outro']},catalog).length"),0);assert.equal(run("suggestedTests({servicos:[]},catalog).length"),0);});
test('vínculos de componentes são normalizados e preservados no snapshot de execução',()=>{const run=store();assert.equal(run("normalizeTestComponents(' api-credito, API-CREDITO, , web-credito ').join(',')"),'API-CREDITO,web-credito');run("var caso={id:'a',nome:'Teste',tipo:'Manual',etapaAlvo:'Simulação',componentes:['api-credito']};var sc=newTestExecution(caso);caso.componentes.push('web-credito')");assert.equal(run('sc.componentes.length'),1);assert.equal(run('sc.componentes[0]'),'api-credito');});
test('filtros combinam pessoa, garantia e etapa final nos casos antigos',()=>{const run=store();assert.equal(run("scenarioCatalog.filter(c=>matchesCaseFilters(c,{etapa:'Desembolso',dimensoes:{Tipo:'PJ',Garantia:'Hipoteca'}})).length"),1);assert.equal(run("scenarioCatalog.filter(c=>matchesCaseFilters(c,{etapa:'Desembolso',dimensoes:{Tipo:'PF',Garantia:'Hipoteca'}})).length"),2);assert.equal(run("caseDimensions({nome:'Assessor - CPR - Alienação'}).Tipo"),undefined);assert.equal(run("matchesCaseFilters({nome:'Assessor - CPR - Alienação'},{dimensoes:{Tipo:'__missing__'}})"),true);});
test('dimensões explícitas prevalecem sobre o nome e correspondência é por segmento completo',()=>{const run=store();assert.equal(run("caseDimensions({nome:'Assessor - CPR - PF - Hipoteca',dimensoes:{Tipo:'PJ',Garantia:'Aval'}}).Tipo"),'PJ');assert.equal(run("matchesCaseFilters({nome:'Assessor - CPR - PF - Hipoteca',dimensoes:{Tipo:'PJ',Garantia:'Aval'}},{dimensoes:{Tipo:'PF'}})"),false);assert.equal(run("caseDimensions({nome:'Assessor E-Finance - CPR GC - PJ - Hipoteca'}).Perfil"),'Assessor E-Finance');assert.equal(run("caseDimensions({nome:'Assessor E-Finance - CPR GC - PJ - Hipoteca'}).Linha"),'CPR GC');});
